name: 'announce-n-crosspost'
description: 'Announce the github release in discord announcement channel and crosspost it to following channels'
branding:
  icon: radio
  color: purple
inputs:
  bot-token:
    description: 'The discord bot token to use for sending the message'
    required: true
  channel:
    description: 'The channel to send and crosspost the message to'
    required: true
  content:
    description: 'The content of the message to send'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'